---
- name: Testing Handlers
  hosts: all
  force_handlers: true
  tasks:
  - block:
    - name: Install flashplayerppapi
      win_chocolatey:
        name: flashplayerpp
        state: present
    rescue:
    - name: Install flashplayerppapi
      win_chocolatey:
        name: flashplayerppapi
        state: absent
    always:
    - name: I am God
      debug:
        msg: no one can stop me, hahaha
    - name: This is a task
      debug:
        msg: hello world