---
- name: Change file ownership and give full control
  hosts: all
  tasks:
  - name: Change owner
    win_owner:
      path: C:\Temp\test.conf
      user: user_train
  - name: Change attribute to FullControl
    win_acl:
      path: C:\Temp\test.conf
      user: user_train
      rights: FullControl
      type: allow
      state: present
