---
- name: Create user and group
  hosts: all
  tasks: 
  - name: Create group
    win_group:
      name: ansible
      description: ansible admin
      state: present
  - name: Create user
    win_user:
      name: ansible
      password: ansible
      state: present
      group: ansible
...  