---
- name: Testing Handlers
  hosts: all
  force_handlers: true
  tasks:
  - name: Install flashplayerppapi
    win_chocolatey:
      name: flashplayerppapi
      state: present
    notify:
      - reboot server
  - name: failing the task
    debug:
      msg: failling the task as testing requires
    failed_when: true
  - name: This is another task
    debug:
      msg: final task
  handlers:
  - name: reboot server
    win_reboot: