---
- name: Testing Handlers
  hosts: all
  tasks:
  - name: Install vlc
    win_chocolatey:
      name: vlc
      state: present
    notify:
      - reboot server
  - name: failing the task
    fail:
      msg: failling the task as testing requires
  handlers:
  - name: reboot server
    win_reboot: